import type { Metadata } from "next";
import "./globals.css";
import {Rubik_Mono_One} from "next/font/google";
import { ThemeProvider } from "next-themes";


const rubik = Rubik_Mono_One({
  subsets: ["latin"], // Load required subsets
  weight: "400", // Rubik Mono One only supports weight 400
  variable: "--font-rubik-mono-one", // Define CSS variable
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${rubik.variable} scroll-smooth antialiased`}
      >< ThemeProvider attribute="class">
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
